
SELECT SUM(TIV_2016) AS TIV_2016
FROM 
    insurance
    LEFT JOIN (SELECT TIV_2015, COUNT(*) AS f1 FROM insurance GROUP BY TIV_2015) a USING (TIV_2015)
    LEFT JOIN (SELECT LAT, LON, COUNT(*) AS f2 FROM insurance GROUP BY LAT, LON) b USING (LAT, LON)
WHERE
    f1 > 1 AND f2 = 1; 






SELECT SUM(TIV_2016) AS TIV_2016
FROM insurance
WHERE
    TIV_2015 IN (SELECT TIV_2015 FROM insurance GROUP BY TIV_2015 HAVING COUNT(*) > 1)
AND
    CONCAT(LAT, LON) IN (SELECT CONCAT(LAT, LON) FROM insurance GROUP BY LAT, LON HAVING COUNT(*) = 1); 
